import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Visualizer Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-50 to-slate-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Estudio Cactus{" "}
            <span className="text-[hsl(280,43%,26%)]">Visualizer</span> Test
          </h1>
          <div>
            <Link
              className="flex max-w-xs flex-col  gap-4 rounded-xl bg-black/10 p-4  text-black hover:bg-black/20"
              href="/visualizer"
            >
              <h3 className="text-2xl font-bold">Start →</h3>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
